services:
  - type: web
    name: SavingFromFormData
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: dotenv
        value: Hakr
    healthCheckPath: /
    port: 5000
