services:
  - type: web
    blueprint: SavingFromFormData
    name: SavingFromFormData
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: dotenv
        value: Hakr
        
