services:
  - type: web
    name: SavingFromFormData
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: dotenv
        value: Hakr
    healthCheckPath: /
